name: file-path-th
version: 0.1.0.0
maintainer: Dan Fithian
license: MIT
license-file: LICENSE
synopsis: Template Haskell utilities for filepaths.
description: Template Haskell utilities for filepaths. This package has utilities for embedding relative filepaths using Template Haskell.
category: System
github: Simspace/file-path-th

default-extensions:
  - ConstraintKinds
  - DataKinds
  - DeriveDataTypeable
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - GeneralizedNewtypeDeriving
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - NoMonomorphismRestriction
  - OverloadedStrings
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - TupleSections
  - TypeFamilies
  - ViewPatterns

ghc-options:
  - -Wall
  - -fwarn-tabs

dependencies:
  - base < 5.0
  - directory
  - file-embed
  - filepath
  - template-haskell

library:
  source-dirs: [src]
